
package org.soa.ws.tp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MakerImplService", targetNamespace = "http://tp.ws.soa.org/", wsdlLocation = "http://localhost:1234/Maker?wsdl")
public class MakerImplService
    extends Service
{

    private final static URL MAKERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAKERIMPLSERVICE_EXCEPTION;
    private final static QName MAKERIMPLSERVICE_QNAME = new QName("http://tp.ws.soa.org/", "MakerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/Maker?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAKERIMPLSERVICE_WSDL_LOCATION = url;
        MAKERIMPLSERVICE_EXCEPTION = e;
    }

    public MakerImplService() {
        super(__getWsdlLocation(), MAKERIMPLSERVICE_QNAME);
    }

    public MakerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAKERIMPLSERVICE_QNAME, features);
    }

    public MakerImplService(URL wsdlLocation) {
        super(wsdlLocation, MAKERIMPLSERVICE_QNAME);
    }

    public MakerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAKERIMPLSERVICE_QNAME, features);
    }

    public MakerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MakerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MiltiServise
     */
    @WebEndpoint(name = "MakerImplPort")
    public MiltiServise getMakerImplPort() {
        return super.getPort(new QName("http://tp.ws.soa.org/", "MakerImplPort"), MiltiServise.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MiltiServise
     */
    @WebEndpoint(name = "MakerImplPort")
    public MiltiServise getMakerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tp.ws.soa.org/", "MakerImplPort"), MiltiServise.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAKERIMPLSERVICE_EXCEPTION!= null) {
            throw MAKERIMPLSERVICE_EXCEPTION;
        }
        return MAKERIMPLSERVICE_WSDL_LOCATION;
    }

}
