
package org.soa.ws.tp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MiltiServise", targetNamespace = "http://tp.ws.soa.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MiltiServise {


    /**
     * 
     * @param lower
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "toUpper", targetNamespace = "")
    @RequestWrapper(localName = "toUpperString", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.ToUpperString")
    @ResponseWrapper(localName = "toUpperStringResponse", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.ToUpperStringResponse")
    @Action(input = "http://tp.ws.soa.org/MiltiServise/toUpperStringRequest", output = "http://tp.ws.soa.org/MiltiServise/toUpperStringResponse")
    public String toUpperString(
        @WebParam(name = "Lower", targetNamespace = "")
        String lower);

    /**
     * 
     * @param val4
     * @param val3
     * @param val2
     * @param val1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "Moy", targetNamespace = "")
    @RequestWrapper(localName = "getMoyValue", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.GetMoyValue")
    @ResponseWrapper(localName = "getMoyValueResponse", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.GetMoyValueResponse")
    @Action(input = "http://tp.ws.soa.org/MiltiServise/getMoyValueRequest", output = "http://tp.ws.soa.org/MiltiServise/getMoyValueResponse")
    public double getMoyValue(
        @WebParam(name = "val_1", targetNamespace = "")
        double val1,
        @WebParam(name = "val_2", targetNamespace = "")
        double val2,
        @WebParam(name = "val_3", targetNamespace = "")
        double val3,
        @WebParam(name = "val_4", targetNamespace = "")
        double val4);

    /**
     * 
     * @param upper
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "toLower", targetNamespace = "")
    @RequestWrapper(localName = "toLowerString", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.ToLowerString")
    @ResponseWrapper(localName = "toLowerStringResponse", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.ToLowerStringResponse")
    @Action(input = "http://tp.ws.soa.org/MiltiServise/toLowerStringRequest", output = "http://tp.ws.soa.org/MiltiServise/toLowerStringResponse")
    public String toLowerString(
        @WebParam(name = "Upper", targetNamespace = "")
        String upper);

    /**
     * 
     * @param val2
     * @param val1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "Max", targetNamespace = "")
    @RequestWrapper(localName = "getMaxValue", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.GetMaxValue")
    @ResponseWrapper(localName = "getMaxValueResponse", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.GetMaxValueResponse")
    @Action(input = "http://tp.ws.soa.org/MiltiServise/getMaxValueRequest", output = "http://tp.ws.soa.org/MiltiServise/getMaxValueResponse")
    public double getMaxValue(
        @WebParam(name = "val_1", targetNamespace = "")
        double val1,
        @WebParam(name = "val_2", targetNamespace = "")
        double val2);

    /**
     * 
     * @param val2
     * @param val1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "Min", targetNamespace = "")
    @RequestWrapper(localName = "getMinValue", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.GetMinValue")
    @ResponseWrapper(localName = "getMinValueResponse", targetNamespace = "http://tp.ws.soa.org/", className = "org.soa.ws.tp.GetMinValueResponse")
    @Action(input = "http://tp.ws.soa.org/MiltiServise/getMinValueRequest", output = "http://tp.ws.soa.org/MiltiServise/getMinValueResponse")
    public double getMinValue(
        @WebParam(name = "val_1", targetNamespace = "")
        double val1,
        @WebParam(name = "val_2", targetNamespace = "")
        double val2);

}
